# neat-eon
wandb_artefact: "novae/novae/model-npe8aft1:v23"

data:
  train_dataset: /gpfs/workdir/blampeyq/res_novae/X_scConcept2
  val_dataset: /gpfs/workdir/blampeyq/res_novae/X_scConcept2_validation2

fit_kwargs:
  max_epochs: 40
  lr: 0.00003
  accelerator: "gpu"
  num_workers: 8
  patience: 6
  min_delta: 0.025

post_training:
  n_domains: [15, 20, 25]
  log_metrics: true
  log_umap: true
  log_domains: true
  delete_X: true
